config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :organizations, only: [:index, :create, :edit, :update, :destroy]
  resources :shifts,        only: [:index, :create, :edit, :update, :destroy]

  scope module: :users, path: 'users' do
    resource :join_organization,  only: :update
    resource :leave_organization, only: :update
    resource :update_accounts,    only: [:edit, :update]
  end

  root to: 'organizations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organization.rb
class Organization < ApplicationRecord
  validates :name, presence: true
  validates :hourly_rate, numericality: { greater_than: 0 }

  has_many :users, dependent: :nullify
  has_many :shifts, through: :users
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :user
  delegate :organization, to: :user

  def shift_length
    self.finish - self.start
  end

  def hours_worked
    seconds_worked = shift_length - (self.break_length * 60)
    (seconds_worked / 3600).round(2)
  end

  def shift_cost
    (hours_worked * self.organization.hourly_rate).round(2)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :organization, optional: true

  has_many :shifts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  layout :layout_by_resource

  def layout_by_resource
    devise_controller? ? 'devise' : 'application'
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:edit, :update, :destroy]

  def index
    @organizations = Organization.all
    @organization  = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      redirect_to organizations_path
    else
      render :index
    end
  end

  def edit
  end

  def update
    if @organization.update(organization_params)
      redirect_to organizations_path
    else
      render :edit
    end
  end

  def destroy
    if @organization.destroy
      redirect_to organizations_path
    else
      render :edit
    end
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :hourly_rate)
  end

  def set_organization
    @organization = Organization.find(params[:id])
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def index
    if current_user.organization.nil?
      redirect_to root_path
    else
      @q      = current_user.organization.shifts.ransack(params[:q])
      @shifts = @q.result.includes(:user).order(:start).reverse
      @shift  = ShiftForm.new
    end
  end

  def create
    @shift = ShiftForm.new(shift_params)
    if @shift.save
      redirect_to shifts_path
    end
  end

  def edit
    @shift = ShiftForm.new(shift: shift)
  end

  def update
    @shift = ShiftForm.new(shift_params.merge(shift: shift))
    if @shift.update
      redirect_to shifts_path
    else
      render :edit
    end
  end

  def destroy
    if shift.destroy
      redirect_to shifts_path
    end
  end

  private

  def shift_params
    params.require(:shift)
      .permit(:shift_date, :start, :finish, :break_length)
      .merge(user_id: current_user.id)
  end 

  def shift
    Shift.find(params[:id])
  end
end

app/controllers/users/join_organizations_controller.rb
module Users
  class JoinOrganizationsController < ApplicationController
    def update
      if current_user.update organization: organization
        redirect_to root_path
      end
    end

    private

    def organization
      Organization.find(params[:organization_id])
    end
  end
end

app/controllers/users/leave_organizations_controller.rb
module Users
  class LeaveOrganizationsController < ApplicationController
    def update
      if current_user.update organization: nil
        redirect_to organizations_path
      end
    end
  end
end

app/controllers/users/update_accounts_controller.rb
module Users
  class UpdateAccountsController < ApplicationController
    def edit
      @user = UserForm.new(user: current_user)
    end

    def update
      @user = UserForm.new(user_params)
      if @user.update
        redirect_to root_path
      else
        render :edit
      end
    end

    private

    def user_params
      params.require(:user)
        .permit(:name, :email, :password, :password_confirmation, :old_password)
        .merge(user_id: current_user.id, user: current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adnat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1><%= link_to 'Adnat', root_path %></h1>
    <p>Logged in as <%= current_user.name %>, <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></p>
    <p><%= link_to 'Update User Account', edit_update_accounts_path %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adnat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1><%= link_to 'Adnat', root_path %></h1>
    <%= yield %>
  </body>
</html>

app/views/organizations/edit.slim
h4 Edit Organization
= simple_form_for @organization, url: organization_path(@organization), method: :patch do |f|
  = f.input :name
  = f.input :hourly_rate
  = f.button :submit
= link_to 'Delete', organization_path(@organization), method: :delete

app/views/organizations/index.slim
- if current_user.organization.nil?
  h3 Organizations
  p You aren't a member of any organization. Join an existing one or create a new one.
  - if @organizations.present?
    ul
      - @organizations.each do |organization|
        - edit_path = edit_organization_path(organization)
        - join_path = join_organization_path(organization_id: organization.id)
        li= "#{organization.name} #{link_to 'Edit', edit_path} #{link_to 'Join', join_path, method: :patch}".html_safe
  h3 Create Organization
  = simple_form_for @organization do |f|
    = f.input  :name
    = f.input  :hourly_rate
    = f.button :submit
- else
  h3= current_user.organization.name
  = link_to 'View Shifts', shifts_path
  br
  = link_to 'Edit', edit_organization_path(current_user.organization)
  br
  = link_to 'Leave', leave_organization_path, method: :patch

app/views/shifts/edit.slim
h4 Edit Shift
= simple_form_for @shift, url: shift_path(id: @shift.shift.id), method: :put do |f|
  = f.input :shift_date
  = f.input :start
  = f.input :finish
  = f.input :break_length
  = f.submit 'Update Shift'

app/views/shifts/index.slim
h3= current_user.organization.name
h4 Shifts
= search_form_for @q do |f|
  = f.search_field :user_name_cont, placeholder: 'Search a name...'
br
table border='1'
  thead
    tr
      th Employee Name
      th Shift Date
      th Start Time
      th End Time
      th Break Length (Minutes)
      th Hours Worked
      th Shift Cost
      th Actions
  tbody
    - @shifts.each do |shift|
      tr
        td= shift.user.name
        td= shift.start.to_date
        td= shift.start.strftime('%I:%M %p')
        td= shift.finish.strftime('%I:%M %p')
        td= shift.break_length
        td= shift.hours_worked
        td= number_to_currency(shift.shift_cost)
        td
          = link_to 'Edit', edit_shift_path(shift), style: 'margin-right: 4px;'
          = link_to 'Delete', shift_path(shift), method: :delete
    tr
      = form_for @shift, url: shifts_path, method: :post do |f|
        td= current_user.name
        td= f.date_field :shift_date
        td= f.time_field :start
        td= f.time_field :finish
        td= f.number_field :break_length
        td colspan='2'
          = f.submit

app/views/users/update_accounts/edit.slim
h3 Update Account
= simple_form_for @user, url: update_accounts_path, method: :put do |f|
  = f.input :name
  = f.input :email
  = f.input :old_password
  = f.input :password
  = f.input :password_confirmation
  = f.button :submit, 'Update User'